# Site settings
title: "Onurcan Bektas: Personal Webpage"
description: "A blog about anything I'm interested in"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://onurcanbektas.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: onurcan bektas
user_title: Onurcan Bektas
email: &#x62&#x6b&#x74&#x73&#x6f&#x6e&#x75&#x72&#x63&#x61&#x6e&#x5b&#x73&#x6e&#x61&#x69&#x6c&#x5d&#x5b&#x67&#x5d&#x5b&#x6d&#x5d&#x5b&#x61&#x5d&#x5b&#x69&#x5d&#x5b&#x6c&#x5d&#x
twitter_username: onurcanbkts
github_username:  onurcanbektas
#gplus_username:  loremipsum
linkedin_public_url: onurcanbektas # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: https-onurcanbektas-github-io
profile_picture: ./assets/img/Unknown.jpg


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: about me
      url: /about
      key_trigger: 3

# projects in header index
projects:
  - name: 
    url: 

# exclude my node related stuff
exclude: ['package.json', 'src' ,'node_modules']
