project:
  type: website

format:
  html:
    theme: [Lumen, theme.scss]
    css: styles.css

editor: visual

website:
  title: "Home"
  site-url: https://onurcanbektas.quarto.pub/home/
  description: "Personal webspage"
  navbar:
    right:
      - about.qmd
      - research_projects.qmd
      - side_projects.qmd

