---
title: "Projects"
---

## Fast utility functions 
R language, however great, is sometimes too slow to handle calculations done on millions of rows of data.
In such cases, it is faster to call an external compiled function directly from R to streamline the data analysis without needing to switch to another language.
In that spirit, I implemented a set of such functions in Rust and made it available as a [R package](http://localhost:5794/projects.html).
The package itself mostly contains connected correlation functions that can use different metrics.
Please see the [README](https://gitlab.com/onurcanbektas/bektas.utils.r/-/blob/main/README.md?ref_type=heads) for how to use it, and the man pages for more details on the implemented functions.

## 1D interacting stochastic many-body particle system
The studying interacting stochastic many-body particle systems analytically is quite limited to a few simple cases.
As a result, it is imperative to study such complex systems numerically.
However, these simulations can take up hours if not days, due to the sheer number of particles that might be needed in the simulations.
Here, I started implementing one such [codebase in Rust](https://gitlab.com/onurcanbektas/langevin_many_body) that can be extended and optimised for such purposes.

Moreover, I'm now developing a GPU-accelerated version of this codebase in order to simulate 10M particles under a day using Apple GPUs.
This work is still in progress.

